all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ./ansible/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  hosts:
    demo-node-1:
      ansible_host: 127.0.0.1
      ansible_port: 2221
    demo-node-2:
      ansible_host: 127.0.0.1
      ansible_port: 2222
